'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'bn' | 'mr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.assistant': 'AI Assistant',
    'nav.timeline': 'Timeline',
    'nav.quiz': 'Quiz',
    'nav.checklist': 'Checklist',
    'nav.map': 'Booth Map',
    'hero.title': 'Your Voice, Your Vote',
    'hero.subtitle': 'The AI-powered guide for Indian voters. Get informed, get registered, and get ready to vote.',
    'hero.cta': 'Start Your Journey',
    'hero.cta2': 'Ask Assistant',
    'hero.badge': 'Next-Generation Election Assistant',
    'features.assistant.title': 'AI Election Assistant',
    'features.assistant.desc': 'Ask questions in your preferred language about voting processes.',
    'features.timeline.title': 'Voter Timeline',
    'features.timeline.desc': 'Track the complete election process from registration to results day.',
    'features.checklist.title': 'First-Time Voter Guide',
    'features.checklist.desc': 'Step-by-step checklist to get registered and cast your first vote.',
    'features.map.title': 'Locate Polling Booth',
    'features.map.desc': 'Find polling booths near you with interactive maps and directions.',
    'explore': 'Explore',
    'checklist.title': 'First-Time Voter Journey',
    'checklist.subtitle': 'Your step-by-step checklist to become a registered voter in India.',
    'checklist.progress': 'Your Progress',
    'checklist.step': 'Step',
    'checklist.completed': 'steps completed',
    'timeline.title': 'Election Timeline',
    'timeline.subtitle': 'Understand the phases of the democratic process in India.',
    'timeline.badge': 'Understand The Process',
    'quiz.title': 'Voter Awareness Quiz',
    'quiz.subtitle': 'Test your knowledge about the Indian electoral process!',
    'map.title': 'Locate Polling Booths',
    'map.subtitle': 'Find election polling booths near your current location.',
    'map.detecting': 'Detecting location...',
    'map.findNearest': 'Find Nearest Booths',
    'map.searchPlaceholder': 'Search booths or areas...',
    'map.noLocation': 'No Location Detected',
    'map.noLocationDesc': 'Click the button above to discover polling stations within your constituency.',
    'map.noResults': 'No booths found matching your search.',
    'map.recommended': 'Recommended',
    'map.getDirections': 'Get Directions',
    'map.navigate': 'Navigate',
    'map.loadingEngine': 'Loading Map Engine...',
    'map.connectingApi': 'Connecting to Google Maps API',
    'map.recenter': 'Re-center to my location',
    'map.crowd.low': 'Low',
    'map.crowd.medium': 'Medium',
    'map.crowd.high': 'High',
    'assistant.title': 'VoteIndia Assistant',
    'assistant.subtitle': 'Powered by Google AI',
    'assistant.placeholder': 'Type your question here...',
    'assistant.greeting': 'Namaste! I am your AI Election Assistant. How can I help you with your voter journey today?',
    'assistant.suggestions.1': 'How do I register to vote?',
    'assistant.suggestions.2': 'What documents do I need?',
    'assistant.suggestions.3': 'How to check my name in the voter list?',
    'assistant.suggestions.4': 'What is the voting age in India?',
    'timeline.event.1.title': 'Voter Registration',
    'timeline.event.1.date': 'Ongoing - Stops before elections',
    'timeline.event.1.desc': 'Ensure your name is on the electoral roll. Apply via Form 6 if you are a new voter.',
    'timeline.event.2.title': 'Election Schedule Announcement',
    'timeline.event.2.date': 'Model Code of Conduct kicks in',
    'timeline.event.2.desc': 'The Election Commission of India (ECI) announces the polling dates, phases, and counting day.',
    'timeline.event.3.title': 'Campaigning Period',
    'timeline.event.3.date': 'Ends 48 hours before polling',
    'timeline.event.3.desc': 'Candidates campaign and release manifestos. Time for you to research the candidates in your constituency.',
    'timeline.event.4.title': 'Voting Day (Polling)',
    'timeline.event.4.date': 'As per your phase/constituency',
    'timeline.event.4.desc': 'Go to your designated polling booth. Press the button against the candidate of your choice on the EVM.',
    'timeline.event.5.title': 'Counting and Results',
    'timeline.event.5.date': 'Usually 2-3 weeks after Phase 1',
    'timeline.event.5.desc': 'Votes are counted, and results are declared by the ECI.',
    'quiz.q1.question': 'What is the minimum voting age in India?',
    'quiz.q1.options': '16 years, 18 years, 21 years, 25 years',
    'quiz.q1.explanation': 'The 61st Amendment Act of 1988 lowered the voting age from 21 to 18 years.',
    'quiz.q2.question': 'Which form is used to register as a new voter?',
    'quiz.q2.options': 'Form 6, Form 7, Form 8, Form 6A',
    'quiz.q2.explanation': 'Form 6 is used for the inclusion of a name in the electoral roll for first-time voters.',
    'quiz.q3.question': 'What does NOTA stand for?',
    'quiz.q3.options': 'None Of The Approved, No Other True Alternative, None Of The Above, Next Of The Above',
    'quiz.q3.explanation': 'NOTA (None Of The Above) allows voters to officially reject all candidates running in an election.',
    'quiz.q4.question': 'Who conducts the Lok Sabha elections in India?',
    'quiz.q4.options': 'President of India, Supreme Court, Election Commission of India, Parliament',
    'quiz.q4.explanation': 'The Election Commission of India is an autonomous constitutional authority responsible for administering election processes in India.',
    'quiz.q5.question': 'What is EPIC?',
    'quiz.q5.options': 'Electoral Photo Identity Card, Election Panel Information Card, Electronic Polling Identification Card, Electoral Process in India Council',
    'quiz.q5.explanation': 'EPIC is the official term for the Voter ID Card issued by the Election Commission of India.',
    'quiz.result.completed': 'Quiz Completed!',
    'quiz.result.score': 'You scored',
    'quiz.result.outOf': 'out of',
    'quiz.result.perfect': '🏆 Flawless victory! You are a fully informed voter ready for the elections!',
    'quiz.result.good': '👍 Great job! You have a solid understanding of the voting process.',
    'quiz.result.learn': '📚 Keep learning! Use our AI Assistant to clarify your doubts about voting.',
    'quiz.result.retry': 'Retake Quiz',
    'quiz.next': 'Next Question',
    'quiz.results': 'See Results',
    'quiz.explanation': 'Explanation',
    'checklist.profile.title': 'Personalize your voter journey',
    'checklist.profile.age': 'What is your age?',
    'checklist.profile.agePlaceholder': 'Must be 18+',
    'checklist.profile.firstTime': 'Are you a first-time voter?',
    'checklist.profile.yes': 'Yes, I am a first-time voter',
    'checklist.profile.no': 'No, I have voted before',
    'checklist.profile.state': 'Which State/UT do you live in?',
    'checklist.profile.statePlaceholder': 'e.g. Maharashtra, Delhi...',
    'checklist.profile.submit': 'Generate Smart Checklist',
    'checklist.readiness': 'Readiness Score',
    'checklist.done': 'Mark as Done',
    'checklist.complete.title': 'You are Election Ready! 🎉',
    'checklist.complete.desc': 'Your profile is 100% complete. Your voice matters, make sure you go out and vote!',
    'checklist.step1.title': 'Check Eligibility',
    'checklist.step1.desc': 'Ensure you are an Indian citizen and 18+ years of age on the qualifying date.',
    'checklist.step1.details': 'You cannot vote if you are disqualified due to certain offenses or corrupt practices.',
    'checklist.step2.title': 'Gather Documents',
    'checklist.step2.desc': 'Collect your age and address proofs.',
    'checklist.step2.details': 'Valid proofs include Aadhaar Card, Passport, Driving License, PAN Card, or 10th/12th certificate.',
    'checklist.step3.title': 'Fill Form 6',
    'checklist.step3.desc': 'Apply online on the Voter Service Portal or offline through your BLO.',
    'checklist.step3.details': 'Go to voters.eci.gov.in, register/login, and fill out Form 6 for new voter registration. Upload your photo and documents.',
    'checklist.step4.title': 'Verification',
    'checklist.step4.desc': 'Booth Level Officer (BLO) will verify your details.',
    'checklist.step4.details': 'A BLO might visit your address to verify the provided details. Keep your original documents handy.',
    'checklist.step5.title': 'Get Voter ID (EPIC)',
    'checklist.step5.desc': 'Download e-EPIC or wait for physical delivery.',
    'checklist.step5.details': 'Once approved, your name will be added to the electoral roll. You can download the digital copy (e-EPIC) from the portal.',
    'checklist.step6.title': 'Vote on Election Day',
    'checklist.step6.desc': 'Find your polling booth and cast your vote!',
    'checklist.step6.details': 'Check your name on the voter slip, take your EPIC or another valid ID, and press the button on the EVM!',
    'features.section.title': 'Powerful Features for the Modern Voter',
    'features.section.subtitle': 'Everything you need to participate in the world\'s largest democracy, simplified by AI.',
    'stats.voters.label': 'Active Voters',
    'stats.voters.value': '960M+',
    'stats.stations.label': 'Polling Stations',
    'stats.stations.value': '1M+',
    'stats.queries.label': 'AI Queries Solved',
    'stats.queries.value': '500K+',
    'stats.languages.label': 'Languages Supported',
    'stats.languages.value': '12+',
    'how.title': 'Your Journey to the Ballot',
    'how.step1.title': 'Register',
    'how.step1.desc': 'Create your profile and check your eligibility for the upcoming elections.',
    'how.step2.title': 'Verify',
    'how.step2.desc': 'Use our AI assistant to understand which documents you need and how to apply.',
    'how.step3.title': 'Prepare',
    'how.step3.desc': 'Track important dates and find your polling booth with our interactive map.',
    'how.step4.title': 'Vote',
    'how.step4.desc': 'Go out and make your voice heard. Your vote shapes the future of the nation.',
    'cta.title': 'Ready to Shape the Future?',
    'cta.desc': 'Join millions of Indian citizens in the world\'s largest democratic exercise. Your journey starts here.',
    'cta.reg': 'Get Registered Now',
    'cta.learn': 'Learn More',
    'hero.scroll': 'Scroll to Explore'
  },
  hi: {
    'nav.home': 'मुख्य पृष्ठ',
    'nav.assistant': 'एआई सहायक',
    'nav.timeline': 'समयरेखा',
    'nav.quiz': 'प्रश्नोत्तरी',
    'nav.checklist': 'चेकलिस्ट',
    'nav.map': 'बूथ मैप',
    'hero.title': 'आपकी आवाज़, आपका वोट',
    'hero.subtitle': 'भारतीय मतदाताओं के लिए एआई-संचालित मार्गदर्शिका। जानकारी प्राप्त करें और मतदान के लिए तैयार रहें।',
    'hero.cta': 'अपनी यात्रा शुरू करें',
    'hero.cta2': 'सहायक से पूछें',
    'hero.badge': 'अगली पीढ़ी का चुनाव सहायक',
    'features.assistant.title': 'एआई चुनाव सहायक',
    'features.assistant.desc': 'मतदान प्रक्रियाओं के बारे में अपनी पसंदीदा भाषा में प्रश्न पूछें।',
    'features.timeline.title': 'मतदाता समयरेखा',
    'features.timeline.desc': 'पंजीकरण से परिणाम के दिन तक चुनाव प्रक्रिया को ट्रैक करें।',
    'features.checklist.title': 'पहली बार मतदाता मार्गदर्शिका',
    'features.checklist.desc': 'पंजीकरण करने और अपना पहला वोट डालने के लिए चरण-दर-चरण चेकलिस्ट।',
    'features.map.title': 'मतदान केंद्र खोजें',
    'features.map.desc': 'इंटरैक्टिव मानचित्रों के साथ अपने आस-पास मतदान केंद्र खोजें।',
    'explore': 'और जानें',
    'checklist.title': 'पहली बार मतदाता यात्रा',
    'checklist.subtitle': 'भारत में पंजीकृत मतदाता बनने के लिए आपकी चरण-दर-चरण चेकलिस्ट।',
    'checklist.progress': 'आपकी प्रगति',
    'checklist.step': 'चरण',
    'checklist.completed': 'चरण पूरे हुए',
    'timeline.title': 'चुनाव समयरेखा',
    'timeline.subtitle': 'भारत में लोकतांत्रिक प्रक्रिया के चरणों को समझें।',
    'timeline.badge': 'प्रक्रिया को समझें',
    'quiz.title': 'मतदाता जागरूकता प्रश्नोत्तरी',
    'quiz.subtitle': 'भारतीय चुनाव प्रक्रिया के बारे में अपने ज्ञान का परीक्षण करें!',
    'map.title': 'मतदान केंद्र खोजें',
    'map.subtitle': 'अपने वर्तमान स्थान के पास चुनाव मतदान केंद्र खोजें।',
    'map.detecting': 'स्थान का पता लगाया जा रहा है...',
    'map.findNearest': 'निकटतम बूथ खोजें',
    'map.searchPlaceholder': 'बूथ या क्षेत्र खोजें...',
    'map.noLocation': 'कोई स्थान नहीं मिला',
    'map.noLocationDesc': 'अपने निर्वाचन क्षेत्र के भीतर मतदान केंद्रों को खोजने के लिए ऊपर दिए गए बटन पर क्लिक करें।',
    'map.noResults': 'आपकी खोज से मेल खाने वाला कोई बूथ नहीं मिला।',
    'map.recommended': 'अनुशंसित',
    'map.getDirections': 'दिशा-निर्देश प्राप्त करें',
    'map.navigate': 'नेविगेट करें',
    'map.loadingEngine': 'मैप इंजन लोड हो रहा है...',
    'map.connectingApi': 'गूगल मैप्स एपीआई से जुड़ रहा है',
    'map.recenter': 'मेरे स्थान पर फिर से केंद्रित करें',
    'map.crowd.low': 'कम भीड़',
    'map.crowd.medium': 'मध्यम भीड़',
    'map.crowd.high': 'अधिक भीड़',
    'assistant.title': 'वोट इंडिया सहायक',
    'assistant.subtitle': 'Google AI द्वारा संचालित',
    'assistant.placeholder': 'अपना प्रश्न यहाँ टाइप करें...',
    'assistant.listening': 'सुन रहा हूँ...',
    'assistant.greeting': 'नमस्ते! मैं आपका एआई चुनाव सहायक हूँ। आज मैं आपकी मतदाता यात्रा में कैसे मदद कर सकता हूँ?',
    'assistant.suggestions.1': 'मैं मतदान के लिए पंजीकरण कैसे करूँ?',
    'assistant.suggestions.2': 'मुझे किन दस्तावेज़ों की आवश्यकता है?',
    'assistant.suggestions.3': 'मतदाता सूची में अपना नाम कैसे जाँचे?',
    'assistant.suggestions.4': 'भारत में मतदान की आयु क्या है?',
    'timeline.event.1.title': 'मतदाता पंजीकरण',
    'timeline.event.1.date': 'निरंतर - चुनाव से पहले रुक जाता है',
    'timeline.event.1.desc': 'सुनिश्चित करें कि आपका नाम मतदाता सूची में है। यदि आप नए मतदाता हैं तो फॉर्म 6 के माध्यम से आवेदन करें।',
    'timeline.event.2.title': 'चुनाव कार्यक्रम की घोषणा',
    'timeline.event.2.date': 'आदर्श आचार संहिता लागू',
    'timeline.event.2.desc': 'भारत निर्वाचन आयोग (ECI) मतदान की तारीखों, चरणों और मतगणना के दिन की घोषणा करता है।',
    'timeline.event.3.title': 'प्रचार अवधि',
    'timeline.event.3.date': 'मतदान से 48 घंटे पहले समाप्त',
    'timeline.event.3.desc': 'उम्मीदवार प्रचार करते हैं और घोषणापत्र जारी करते हैं। अपने निर्वाचन क्षेत्र के उम्मीदवारों के बारे में शोध करने का समय।',
    'timeline.event.4.title': 'मतदान का दिन',
    'timeline.event.4.date': 'आपके चरण/निर्वाचन क्षेत्र के अनुसार',
    'timeline.event.4.desc': 'अपने निर्धारित मतदान केंद्र पर जाएं। ईवीएम पर अपनी पसंद के उम्मीदवार के सामने वाला बटन दबाएं।',
    'timeline.event.5.title': 'मतगणना और परिणाम',
    'timeline.event.5.date': 'आमतौर पर पहले चरण के 2-3 सप्ताह बाद',
    'timeline.event.5.desc': 'मतों की गिनती की जाती है, और चुनाव आयोग द्वारा परिणाम घोषित किए जाते हैं।',
    'quiz.q1.question': 'भारत में मतदान की न्यूनतम आयु क्या है?',
    'quiz.q1.options': '16 वर्ष, 18 वर्ष, 21 वर्ष, 25 वर्ष',
    'quiz.q1.explanation': '1988 के 61वें संशोधन अधिनियम ने मतदान की आयु 21 से घटाकर 18 वर्ष कर दी।',
    'quiz.q2.question': 'नए मतदाता के रूप में पंजीकरण करने के लिए किस फॉर्म का उपयोग किया जाता है?',
    'quiz.q2.options': 'फॉर्म 6, फॉर्म 7, फॉर्म 8, फॉर्म 6A',
    'quiz.q2.explanation': 'फॉर्म 6 का उपयोग पहली बार मतदाताओं के लिए मतदाता सूची में नाम शामिल करने के लिए किया जाता है।',
    'quiz.q3.question': 'NOTA का क्या अर्थ है?',
    'quiz.q3.options': 'None Of The Approved, No Other True Alternative, None Of The Above, Next Of The Above',
    'quiz.q3.explanation': 'NOTA (उपरोक्त में से कोई नहीं) मतदाताओं को चुनाव में खड़े सभी उम्मीदवारों को आधिकारिक तौर पर अस्वीकार करने की अनुमति देता है।',
    'quiz.q4.question': 'भारत में लोकसभा चुनाव कौन आयोजित करता है?',
    'quiz.q4.options': 'भारत के राष्ट्रपति, सर्वोच्च न्यायालय, भारत निर्वाचन आयोग, संसद',
    'quiz.q4.explanation': 'भारत निर्वाचन आयोग एक स्वायत्त संवैधानिक प्राधिकरण है जो भारत में चुनाव प्रक्रियाओं के संचालन के लिए जिम्मेदार है।',
    'quiz.q5.question': 'EPIC क्या है?',
    'quiz.q5.options': 'Electoral Photo Identity Card, Election Panel Information Card, Electronic Polling Identification Card, Electoral Process in India Council',
    'quiz.q5.explanation': 'EPIC भारत निर्वाचन आयोग द्वारा जारी मतदाता पहचान पत्र का आधिकारिक नाम है।',
    'quiz.result.completed': 'प्रश्नोत्तरी पूरी हुई!',
    'quiz.result.score': 'आपका स्कोर',
    'quiz.result.outOf': 'में से',
    'quiz.result.perfect': '🏆 शानदार जीत! आप एक पूरी तरह से जागरूक मतदाता हैं जो चुनाव के लिए तैयार हैं!',
    'quiz.result.good': '👍 बहुत बढ़िया! आपको मतदान प्रक्रिया की अच्छी समझ है।',
    'quiz.result.learn': '📚 सीखते रहें! मतदान के बारे में अपनी शंकाओं को दूर करने के लिए हमारे एआई सहायक का उपयोग करें।',
    'quiz.result.retry': 'पुनः प्रयास करें',
    'quiz.next': 'अगला प्रश्न',
    'quiz.results': 'परिणाम देखें',
    'quiz.explanation': 'स्पष्टीकरण',
    'checklist.profile.title': 'अपनी मतदाता यात्रा को व्यक्तिगत बनाएं',
    'checklist.profile.age': 'आपकी उम्र क्या है?',
    'checklist.profile.agePlaceholder': '18+ होना चाहिए',
    'checklist.profile.firstTime': 'क्या आप पहली बार मतदाता हैं?',
    'checklist.profile.yes': 'हाँ, मैं पहली बार मतदाता हूँ',
    'checklist.profile.no': 'नहीं, मैंने पहले भी वोट दिया है',
    'checklist.profile.state': 'आप किस राज्य/केंद्र शासित प्रदेश में रहते हैं?',
    'checklist.profile.statePlaceholder': 'जैसे महाराष्ट्र, दिल्ली...',
    'checklist.profile.submit': 'स्मार्ट चेकलिस्ट जनरेट करें',
    'checklist.readiness': 'तैयारी स्कोर',
    'checklist.done': 'पूरा हुआ चिह्नित करें',
    'checklist.complete.title': 'आप चुनाव के लिए तैयार हैं! 🎉',
    'checklist.complete.desc': 'आपका प्रोफाइल 100% पूरा हो गया है। आपकी आवाज़ मायने रखती है, सुनिश्चित करें कि आप बाहर जाकर वोट दें!',
    'checklist.step1.title': 'पात्रता जांचें',
    'checklist.step1.desc': 'सुनिश्चित करें कि आप एक भारतीय नागरिक हैं और योग्यता तिथि पर 18+ वर्ष के हैं।',
    'checklist.step1.details': 'यदि आप कुछ अपराधों या भ्रष्ट आचरणों के कारण अयोग्य हैं, तो आप वोट नहीं दे सकते।',
    'checklist.step2.title': 'दस्तावेज़ एकत्र करें',
    'checklist.step2.desc': 'अपनी आयु और पते के प्रमाण एकत्र करें।',
    'checklist.step2.details': 'मान्य प्रमाणों में आधार कार्ड, पासपोर्ट, ड्राइविंग लाइसेंस, पैन कार्ड या 10वीं/12वीं का प्रमाण पत्र शामिल हैं।',
    'checklist.step3.title': 'फॉर्म 6 भरें',
    'checklist.step3.desc': 'वोटर सर्विस पोर्टल पर ऑनलाइन या अपने बीएलओ के माध्यम से ऑफलाइन आवेदन करें।',
    'checklist.step3.details': 'voters.eci.gov.in पर जाएं, पंजीकरण/लॉगिन करें और नए मतदाता पंजीकरण के लिए फॉर्म 6 भरें। अपना फोटो और दस्तावेज अपलोड करें।',
    'checklist.step4.title': 'सत्यापन',
    'checklist.step4.desc': 'बूथ लेवल ऑफिसर (BLO) आपके विवरणों का सत्यापन करेंगे।',
    'checklist.step4.details': 'एक बीएलओ दिए गए विवरणों को सत्यापित करने के लिए आपके पते पर आ सकता है। अपने मूल दस्तावेज पास रखें।',
    'checklist.step5.title': 'वोटर आईडी (EPIC) प्राप्त करें',
    'checklist.step5.desc': 'ई-ईपीआईसी डाउनलोड करें या भौतिक वितरण की प्रतीक्षा करें।',
    'checklist.step5.details': 'एक बार स्वीकृत होने के बाद, आपका नाम मतदाता सूची में जोड़ दिया जाएगा। आप पोर्टल से डिजिटल कॉपी (e-EPIC) डाउनलोड कर सकते हैं।',
    'checklist.step6.title': 'चुनाव के दिन मतदान करें',
    'checklist.step6.desc': 'अपना मतदान केंद्र खोजें और अपना वोट डालें!',
    'checklist.step6.details': 'वोटर स्लिप पर अपना नाम देखें, अपना ईपीआईसी या कोई अन्य मान्य आईडी लें, और ईवीएम पर बटन दबाएं!',
    'features.section.title': 'आधुनिक मतदाता के लिए शक्तिशाली सुविधाएँ',
    'features.section.subtitle': 'दुनिया के सबसे बड़े लोकतंत्र में भाग लेने के लिए आवश्यक सब कुछ, एआई द्वारा सरलीकृत।',
    'stats.voters.label': 'सक्रिय मतदाता',
    'stats.voters.value': '960M+',
    'stats.stations.label': 'मतदान केंद्र',
    'stats.stations.value': '1M+',
    'stats.queries.label': 'एआई प्रश्न हल',
    'stats.queries.value': '500K+',
    'stats.languages.label': 'समर्थित भाषाएँ',
    'stats.languages.value': '12+',
    'how.title': 'मतदान केंद्र तक आपकी यात्रा',
    'how.step1.title': 'पंजीकरण',
    'how.step1.desc': 'अपना प्रोफाइल बनाएं और आगामी चुनावों के लिए अपनी पात्रता जांचें।',
    'how.step2.title': 'सत्यापन',
    'how.step2.desc': 'समझने के लिए हमारे एआई सहायक का उपयोग करें कि आपको किन दस्तावेजों की आवश्यकता है।',
    'how.step3.title': 'तैयारी',
    'how.step3.desc': 'महत्वपूर्ण तिथियों को ट्रैक करें और हमारे मैप के साथ अपना बूथ खोजें।',
    'how.step4.title': 'मतदान',
    'how.step4.desc': 'बाहर जाएं और अपनी आवाज उठाएं। आपका वोट देश का भविष्य तय करता है।',
    'cta.title': 'भविष्य को आकार देने के लिए तैयार हैं?',
    'cta.desc': 'दुनिया के सबसे बड़े लोकतंत्र में शामिल हों। आपकी यात्रा यहाँ से शुरू होती है।',
    'cta.reg': 'अभी पंजीकरण करें',
    'cta.learn': 'और जानें',
    'hero.scroll': 'खोजने के लिए स्क्रॉल करें'
  },
  ta: {
    'nav.home': 'முகப்பு',
    'nav.assistant': 'AI உதவியாளர்',
    'nav.timeline': 'காலவரிசை',
    'nav.quiz': 'வினாடி வினா',
    'nav.checklist': 'சரிபார்ப்பு பட்டியல்',
    'nav.map': 'சாவடி வரைபடம்',
    'hero.title': 'உங்கள் குரல், உங்கள் வாக்கு',
    'hero.subtitle': 'இந்திய வாக்காளர்களுக்கான AI வழிகாட்டி. தகவல்களைப் பெறுங்கள், பதிவு செய்யுங்கள்.',
    'hero.cta': 'தொடங்கவும்',
    'hero.cta2': 'உதவியாளரிடம் கேளுங்கள்',
    'features.assistant.title': 'AI தேர்தல் உதவியாளர்',
    'features.assistant.desc': 'வாக்களிக்கும் முறைகள் பற்றி உங்களுக்கு விருப்பமான மொழியில் கேள்விகளைக் கேளுங்கள்.',
    'features.timeline.title': 'வாக்காளர் காலவரிசை',
    'features.timeline.desc': 'பதிவு முதல் முடிவுகள் வரை தேர்தல் செயல்முறையை கண்காணிக்கவும்.',
    'features.checklist.title': 'முதல் முறை வாக்காளர் வழிகாட்டி',
    'features.checklist.desc': 'பதிவு செய்து வாக்களிக்க படிப்படியான சரிபார்ப்பு பட்டியல்.',
    'features.map.title': 'வாக்குச் சாவடியைக் கண்டறியவும்',
    'features.map.desc': 'உங்கள் அருகிலுள்ள வாக்குச் சாவடிகளைக் கண்டறியவும்.',
    'explore': 'ஆராயுங்கள்',
    'checklist.title': 'முதல் முறை வாக்காளர் பயணம்',
    'checklist.subtitle': 'இந்தியாவில் பதிவு செய்யப்பட்ட வாக்காளராக ஆவதற்கான உங்கள் சரிபார்ப்பு பட்டியல்.',
    'checklist.progress': 'உங்கள் முன்னேற்றம்',
    'checklist.step': 'படி',
    'checklist.completed': 'படிகள் நிறைவடைந்தன',
    'timeline.title': 'தேர்தல் காலவரிசை',
    'timeline.subtitle': 'இந்தியாவில் ஜனநாயக செயல்முறையின் கட்டங்களை புரிந்து கொள்ளுங்கள்.',
    'quiz.title': 'வாக்காளர் விழிப்புணர்வு வினாடி வினா',
    'quiz.subtitle': 'இந்திய தேர்தல் செயல்முறை பற்றிய உங்கள் அறிவை சோதிக்கவும்!',
    'map.title': 'வாக்குச் சாவடிகளைக் கண்டறியவும்',
    'map.subtitle': 'உங்கள் தற்போதைய இருப்பிடத்திற்கு அருகிலுள்ள வாக்குச் சாவடிகளைக் கண்டறியவும்.',
    'assistant.title': 'VoteIndia உதவியாளர்',
    'assistant.subtitle': 'Google AI மூலம் இயக்கப்படுகிறது',
    'assistant.placeholder': 'உங்கள் கேள்வியை இங்கே தட்டச்சு செய்க...',
    'assistant.listening': 'கேட்கிறது...',
    'assistant.greeting': 'வணக்கம்! நான் உங்கள் AI தேர்தல் உதவியாளர். இன்று உங்கள் வாக்காளர் பயணத்தில் நான் எவ்வாறு உதவ முடியும்?',
    'assistant.suggestions.1': 'வாக்களிக்க நான் எவ்வாறு பதிவு செய்வது?',
    'assistant.suggestions.2': 'எனக்கு என்ன ஆவணங்கள் தேவை?',
    'assistant.suggestions.3': 'வாக்காளர் பட்டியலில் என் பெயரை எவ்வாறு சரிபார்ப்பது?',
    'assistant.suggestions.4': 'இந்தியாவில் வாக்களிக்கும் வயது என்ன?',
    'timeline.badge': 'செயல்முறையைப் புரிந்து கொள்ளுங்கள்',
    'timeline.event.1.title': 'வாக்காளர் பதிவு',
    'timeline.event.1.date': 'தொடர்ந்து நடைபெறுகிறது - தேர்தலுக்கு முன் நிறுத்தப்படும்',
    'timeline.event.1.desc': 'வாக்காளர் பட்டியலில் உங்கள் பெயர் இருப்பதை உறுதி செய்யவும். நீங்கள் புதிய வாக்காளராக இருந்தால் படிவம் 6 மூலம் விண்ணப்பிக்கவும்.',
    'timeline.event.2.title': 'தேர்தல் அட்டவணை அறிவிப்பு',
    'timeline.event.2.date': 'மாதிரி நடத்தை விதிமுறை அமலுக்கு வருகிறது',
    'timeline.event.2.desc': 'இந்தியத் தேர்தல் ஆணையம் (ECI) வாக்குப்பதிவு தேதிகள், கட்டங்கள் மற்றும் வாக்கு எண்ணிக்கை நாளை அறிவிக்கிறது.',
    'timeline.event.3.title': 'தேர்தல் பிரச்சார காலம்',
    'timeline.event.3.date': 'வாக்குப்பதிவுக்கு 48 மணி நேரத்திற்கு முன் முடிகிறது',
    'timeline.event.3.desc': 'வேட்பாளர்கள் பிரச்சாரம் செய்து தேர்தல் அறிக்கைகளை வெளியிடுகின்றனர். உங்கள் தொகுதியில் உள்ள வேட்பாளர்களைப் பற்றி ஆராய இதுவே நேரம்.',
    'timeline.event.4.title': 'வாக்குப்பதிவு நாள்',
    'timeline.event.4.date': 'உங்கள் கட்டம்/தொகுதிக்கு ஏற்ப',
    'timeline.event.4.desc': 'உங்களுக்கு ஒதுக்கப்பட்ட வாக்குச் சாவடிக்குச் செல்லுங்கள். EVM-ல் உங்களுக்கு விருப்பமான வேட்பாளருக்கு எதிரான பொத்தானை அழுத்தவும்.',
    'timeline.event.5.title': 'வாக்கு எண்ணிக்கை மற்றும் முடிவுகள்',
    'timeline.event.5.date': 'பொதுவாக முதல் கட்டத்திற்கு 2-3 வாரங்களுக்குப் பிறகு',
    'timeline.event.5.desc': 'வாக்குகள் எண்ணப்பட்டு, தேர்தல் ஆணையத்தால் முடிவுகள் அறிவிக்கப்படுகின்றன.',
    'quiz.q1.question': 'இந்தியாவில் குறைந்தபட்ச வாக்களிக்கும் வயது என்ன?',
    'quiz.q1.options': '16 ஆண்டுகள், 18 ஆண்டுகள், 21 ஆண்டுகள், 25 ஆண்டுகள்',
    'quiz.q1.explanation': '1988-ஆம் ஆண்டின் 61-வது அரசியலமைப்புத் திருத்தச் சட்டம், வாக்களிக்கும் வயதை 21-லிருந்து 18 ஆகக் குறைத்தது.',
    'quiz.q2.question': 'புதிய வாக்காளராகப் பதிவு செய்ய எந்தப் படிவம் பயன்படுத்தப்படுகிறது?',
    'quiz.q2.options': 'படிவம் 6, படிவம் 7, படிவம் 8, படிவம் 6A',
    'quiz.q2.explanation': "முதல்முறை வாக்காளர்கள் தங்கள் பெயரை வாக்காளர் பட்டியலில் சேர்ப்பதற்கு 'படிவம் 6' பயன்படுத்தப்படுகிறது.",
    'quiz.q3.question': 'NOTA என்பதன் விரிவாக்கம் என்ன?',
    'quiz.q3.options': 'மேற்கண்ட எதுவுமில்லை, வேறு மாற்று இல்லை, இவற்றில் எவருமில்லை, அடுத்தவர்',
    'quiz.q3.explanation': 'NOTA (மேற்கூறிய எவரும் இல்லை) என்பது தேர்தலில் போட்டியிடும் அனைத்து வேட்பாளர்களையும் அதிகாரப்பூர்வமாக நிராகரிக்க வாக்காளர்களுக்கு வழிவகுக்கிறது.',
    'quiz.q4.question': 'இந்தியாவில் மக்களவைத் தேர்தலை நடத்துவது யார்?',
    'quiz.q4.options': 'இந்திய ஜனாதிபதி, உச்ச நீதிமன்றம், இந்தியத் தேர்தல் ஆணையம், நாடாளுமன்றம்',
    'quiz.q4.explanation': 'இந்தியத் தேர்தல் ஆணையம் என்பது இந்தியாவில் தேர்தல் செயல்முறைகளை நிர்வகிப்பதற்குப் பொறுப்பான ஒரு தன்னாட்சி பெற்ற அரசியலமைப்பு அதிகார அமைப்பாகும்.',
    'quiz.q5.question': 'EPIC என்றால் என்ன?',
    'quiz.q5.options': 'வாக்காளர் புகைப்பட அடையாள அட்டை, தேர்தல் குழு தகவல் அட்டை, மின்னணு வாக்குப்பதிவு அடையாள அட்டை, தேர்தல் செயல்முறை கவுன்சில்',
    'quiz.q5.explanation': 'EPIC என்பது இந்தியத் தேர்தல் ஆணையத்தால் வழங்கப்படும் வாக்காளர் அடையாள அட்டையின் அதிகாரப்பூர்வ பெயராகும்.',
    'quiz.result.completed': 'வினாடி வினா முடிந்தது!',
    'quiz.result.score': 'உங்கள் மதிப்பெண்',
    'quiz.result.outOf': 'க்கு',
    'quiz.result.perfect': '🏆 அபார வெற்றி! நீங்கள் தேர்தலுக்குத் தயாராக உள்ள முழுமையான விழிப்புணர்வுள்ள வாக்காளர்!',
    'quiz.result.good': '👍 நன்று! வாக்களிக்கும் செயல்முறை குறித்து உங்களுக்கு நல்ல புரிதல் உள்ளது.',
    'quiz.result.learn': '📚 தொடர்ந்து கற்றுக்கொள்ளுங்கள்! உங்கள் சந்தேகங்களைத் தீர்க்க எங்கள் AI உதவியாளரைப் பயன்படுத்தவும்.',
    'quiz.result.retry': 'மீண்டும் முயற்சி செய்',
    'quiz.next': 'அடுத்த கேள்வி',
    'quiz.results': 'முடிவுகளைப் பார்',
    'quiz.explanation': 'விளக்கம்',
    'checklist.profile.title': 'உங்கள் வாக்காளர் பயணத்தைத் தனிப்பயனாக்குங்கள்',
    'checklist.profile.age': 'உங்கள் வயது என்ன?',
    'checklist.profile.agePlaceholder': '18+ இருக்க வேண்டும்',
    'checklist.profile.firstTime': 'நீங்கள் முதல்முறை வாக்காளரா?',
    'checklist.profile.yes': 'ஆம், நான் முதல்முறை வாக்காளர்',
    'checklist.profile.no': 'இல்லை, நான் முன்பே வாக்களித்துள்ளேன்',
    'checklist.profile.state': 'நீங்கள் எந்த மாநிலம்/யூனியன் பிரதேசத்தில் வசிக்கிறீர்கள்?',
    'checklist.profile.statePlaceholder': 'எ.கா. தமிழ்நாடு, புதுச்சேரி...',
    'checklist.profile.submit': 'ஸ்மார்ட் சரிபார்ப்பு பட்டியலை உருவாக்குங்கள்',
    'checklist.readiness': 'தயார்நிலை மதிப்பெண்',
    'checklist.done': 'முடித்ததாகக் குறிக்கவும்',
    'checklist.complete.title': 'நீங்கள் தேர்தலுக்குத் தயாராக உள்ளீர்கள்! 🎉',
    'checklist.complete.desc': 'உங்கள் சுயவிவரம் 100% முடிந்தது. உங்கள் குரல் முக்கியமானது, நீங்கள் வெளியே சென்று வாக்களிப்பதை உறுதிப்படுத்திக் கொள்ளுங்கள்!',
    'checklist.step1.title': 'தகுதியைச் சரிபார்க்கவும்',
    'checklist.step1.desc': 'நீங்கள் இந்தியக் குடிமகனாகவும், தகுதியுள்ள தேதியில் 18 வயதுக்கு மேற்பட்டவராகவும் இருப்பதை உறுதிப்படுத்திக் கொள்ளுங்கள்.',
    'checklist.step1.details': 'குறிப்பிட்ட குற்றங்கள் அல்லது ஊழல் நடைமுறைகள் காரணமாக நீங்கள் தகுதி நீக்கம் செய்யப்பட்டிருந்தால், உங்களால் வாக்களிக்க முடியாது.',
    'checklist.step2.title': 'ஆவணங்களைச் சேகரிக்கவும்',
    'checklist.step2.desc': 'உங்கள் வயது மற்றும் முகவரி சான்றுகளைச் சேகரிக்கவும்.',
    'checklist.step2.details': 'செல்லுபடியாகும் சான்றுகளில் ஆதார் அட்டை, கடவுச்சீட்டு, ஓட்டுநர் உரிமம், பான் கார்டு அல்லது 10/12-ஆம் வகுப்பு சான்றிதழ் ஆகியவை அடங்கும்.',
    'checklist.step3.title': 'படிவம் 6-ஐ நிரப்பவும்',
    'checklist.step3.desc': 'வாக்காளர் சேவை போர்ட்டலில் ஆன்லைனில் அல்லது உங்கள் பிஎல்ஓ மூலம் ஆஃப்லைனில் விண்ணப்பிக்கவும்.',
    'checklist.step3.details': 'voters.eci.gov.in தளத்திற்குச் சென்று, பதிவுசெய்து/உள்நுழைந்து, புதிய வாக்காளர் பதிவிற்கான படிவம் 6-ஐப் பூர்த்தி செய்யவும். உங்கள் புகைப்படம் மற்றும் ஆவணங்களைப் பதிவேற்றவும்.',
    'checklist.step4.title': 'சரிபார்ப்பு',
    'checklist.step4.desc': 'பூத் நிலை அதிகாரி (BLO) உங்கள் விவரங்களைச் சரிபார்ப்பார்.',
    'checklist.step4.details': 'வழங்கப்பட்ட விவரங்களைச் சரிபார்க்க ஒரு பிஎல்ஓ உங்கள் முகவரிக்கு வரலாம். உங்கள் அசல் ஆவணங்களை கையில் வைத்திருங்கள்.',
    'checklist.step5.title': 'வாக்காளர் அடையாள அட்டையைப் (EPIC) பெறவும்',
    'checklist.step5.desc': 'e-EPIC-ஐப் பதிவிறக்கவும் அல்லது அஞ்சலில் வரும் வரை காத்திருக்கவும்.',
    'checklist.step5.details': 'ஒப்புதல் அளிக்கப்பட்டதும், உங்கள் பெயர் வாக்காளர் பட்டியலில் சேர்க்கப்படும். போர்ட்டலில் இருந்து டிஜிட்டல் நகலை (e-EPIC) பதிவிறக்கம் செய்யலாம்.',
    'checklist.step6.title': 'தேர்தல் நாளில் வாக்களியுங்கள்',
    'checklist.step6.desc': 'உங்கள் வாக்குச்சாவடியைக் கண்டறிந்து வாக்களியுங்கள்!',
    'checklist.step6.details': 'வாக்காளர் சீட்டில் உங்கள் பெயரைச் சரிபார்த்து, உங்கள் EPIC அல்லது பிற செல்லுபடியாகும் அடையாள அட்டையை எடுத்துக்கொண்டு, EVM-ல் பொத்தானை அழுத்தவும்!',
    'features.section.title': 'நவீன வாக்காளருக்கான சக்திவாய்ந்த அம்சங்கள்',
    'features.section.subtitle': 'உலகின் மிகப்பெரிய ஜனநாயகத்தில் பங்கேற்க உங்களுக்குத் தேவையான அனைத்தும், AI மூலம் எளிமையாக்கப்பட்டது.',
    'stats.voters.label': 'செயலில் உள்ள வாக்காளர்கள்',
    'stats.voters.value': '960M+',
    'stats.stations.label': 'வாக்குச் சாவடிகள்',
    'stats.stations.value': '1M+',
    'stats.queries.label': 'AI கேள்விகள் தீர்க்கப்பட்டன',
    'stats.queries.value': '500K+',
    'stats.languages.label': 'ஆதரிக்கப்படும் மொழிகள்',
    'stats.languages.value': '12+',
    'how.title': 'வாக்களிப்பதற்கான உங்கள் பயணம்',
    'how.step1.title': 'பதிவு செய்யவும்',
    'how.step1.desc': 'உங்கள் சுயவிவரத்தை உருவாக்கி, வரவிருக்கும் தேர்தல்களுக்கான உங்கள் தகுதியைச் சரிபார்க்கவும்.',
    'how.step2.title': 'சரிபார்க்கவும்',
    'how.step2.desc': 'உங்களுக்கு என்ன ஆவணங்கள் தேவை என்பதைப் புரிந்துகொள்ள எங்களின் AI உதவியாளரைப் பயன்படுத்தவும்.',
    'how.step3.title': 'தயாராகவும்',
    'how.step3.desc': 'முக்கியமான தேதிகளைக் கண்காணித்து, எங்களின் வரைபடம் மூலம் உங்கள் வாக்குச்சாவடியைக் கண்டறியவும்.',
    'how.step4.title': 'வாக்களிக்கவும்',
    'how.step4.desc': 'வெளியே சென்று உங்கள் குரலை பதிவு செய்யுங்கள். உங்கள் வாக்கு நாட்டின் எதிர்காலத்தை தீர்மானிக்கிறது.',
    'cta.title': 'எதிர்காலத்தை வடிவமைக்க தயாரா?',
    'cta.desc': 'உலகின் மிகப்பெரிய ஜனநாயகப் பயிற்சியில் மில்லியன் கணக்கான இந்தியக் குடிமக்களுடன் இணையுங்கள்.',
    'cta.reg': 'இப்போதே பதிவு செய்யுங்கள்',
    'cta.learn': 'மேலும் அறிய',
    'hero.scroll': 'ஆராய கீழே உருட்டவும்'
  },
  te: {
    'nav.home': 'హోమ్',
    'nav.assistant': 'AI అసిస్టెంట్',
    'nav.timeline': 'టైమ్‌లైన్',
    'nav.quiz': 'క్విజ్',
    'nav.checklist': 'చెక్‌లిస్ట్',
    'nav.map': 'బూత్ మ్యాప్',
    'hero.title': 'మీ వాయిస్, మీ ఓటు',
    'hero.subtitle': 'భారతీయ ఓటర్ల కోసం AI గైడ్. సమాచారం పొందండి, నమోదు చేసుకోండి.',
    'hero.cta': 'ప్రారంభించండి',
    'hero.cta2': 'అసిస్టెంట్‌ని అడగండి',
    'features.assistant.title': 'AI ఎన్నికల అసిస్టెంట్',
    'features.assistant.desc': 'ఓటింగ్ ప్రక్రియల గురించి మీకు నచ్చిన భాషలో ప్రశ్నలు అడగండి.',
    'features.timeline.title': 'ఓటరు టైమ్‌లైన్',
    'features.timeline.desc': 'నమోదు నుండి ఫలితాల వరకు ఎన్నికల ప్రక్రియను ట్రాక్ చేయండి.',
    'features.checklist.title': 'మొదటి సారి ఓటరు గైడ్',
    'features.checklist.desc': 'నమోదు చేసుకోవడానికి మరియు ఓటు వేయడానికి దశల వారీ చెక్‌లిస్ట్.',
    'features.map.title': 'పోలింగ్ బూత్‌ను గుర్తించండి',
    'features.map.desc': 'మీకు సమీపంలో ఉన్న పోలింగ్ బూత్‌లను కనుగొనండి.',
    'explore': 'అన్వేషించండి',
    'checklist.title': 'మొదటి సారి ఓటరు ప్రయాణం',
    'checklist.subtitle': 'భారతదేశంలో ఓటరుగా నమోదు కావడానికి మీ చెక్‌లిస్ట్.',
    'checklist.progress': 'మీ పురోగతి',
    'checklist.step': 'దశ',
    'checklist.completed': 'దశలు పూర్తయ్యాయి',
    'timeline.title': 'ఎన్నికల టైమ్‌లైన్',
    'timeline.subtitle': 'భారతదేశంలో ప్రజాస్వామ్య ప్రక్రియను అర్థం చేసుకోండి.',
    'quiz.title': 'ఓటరు అవగాహన క్విజ్',
    'quiz.subtitle': 'ఎన్నికల ప్రక్రియ గురించి మీ జ్ఞానాన్ని పరీక్షించండి!',
    'map.title': 'పోలింగ్ బూత్‌లను గుర్తించండి',
    'map.subtitle': 'మీ ప్రస్తుత ప్రదేశానికి సమీపంలో పోలింగ్ బూత్‌లను కనుగొనండి.',
    'assistant.title': 'VoteIndia అసిస్టెంట్',
    'assistant.subtitle': 'Google AI ద్వారా శక్తిని పొందింది',
    'assistant.placeholder': 'మీ ప్రశ్నను ఇక్కడ టైప్ చేయండి...',
    'assistant.listening': 'వింటున్నాను...',
    'assistant.greeting': 'నమస్కారం! నేను మీ AI ఎన్నికల అసిస్టెంట్‌ని. ఈ రోజు నేను మీకు ఎలా సహాయపడగలను?',
    'assistant.suggestions.1': 'ఓటు వేయడానికి నేను ఎలా నమోదు చేసుకోవాలి?',
    'assistant.suggestions.2': 'నాకు ఏ పత్రాలు కావాలి?',
    'assistant.suggestions.3': 'ఓటరు జాబితాలో నా పేరును ఎలా తనిఖీ చేయాలి?',
    'assistant.suggestions.4': 'భారతదేశంలో ఓటు వేయడానికి కనీస వయస్సు ఎంత?',
    'timeline.badge': 'ప్రక్రియను అర్థం చేసుకోండి',
    'timeline.event.1.title': 'ఓటరు నమోదు',
    'timeline.event.1.date': 'కొనసాగుతోంది - ఎన్నికలకు ముందు నిలిపివేయబడుతుంది',
    'timeline.event.1.desc': 'ఓటరు జాబితాలో మీ పేరు ఉందని నిర్ధారించుకోండి. మీరు కొత్త ఓటరు అయితే ఫారమ్ 6 ద్వారా దరఖాస్తు చేసుకోండి.',
    'timeline.event.2.title': 'ఎన్నికల షెడ్యూల్ ప్రకటన',
    'timeline.event.2.date': 'మోడల్ కోడ్ ఆఫ్ కండక్ట్ అమల్లోకి వస్తుంది',
    'timeline.event.2.desc': 'భారత ఎన్నికల సంఘం (ECI) పోలింగ్ తేదీలు, దశలు మరియు కౌంటింగ్ రోజును ప్రకటిస్తుంది.',
    'timeline.event.3.title': 'ప్రచార కాలం',
    'timeline.event.3.date': 'పోలింగ్‌కు 48 గంటల ముందు ముగుస్తుంది',
    'timeline.event.3.desc': 'అభ్యర్థులు ప్రచారం చేస్తారు మరియు మ్యానిఫెస్టోలను విడుదల చేస్తారు. మీ నియోజకవర్గంలోని అభ్యర్థుల గురించి పరిశోధన చేయడానికి ఇదే సమయం.',
    'timeline.event.4.title': 'పోలింగ్ రోజు',
    'timeline.event.4.date': 'మీ దశ/నియోజకవర్గం ప్రకారం',
    'timeline.event.4.desc': 'మీకు కేటాయించిన పోలింగ్ బూత్‌కు వెళ్లండి. EVMలో మీకు నచ్చిన అభ్యర్థి ఎదురుగా ఉన్న బటన్‌ను నొక్కండి.',
    'timeline.event.5.title': 'కౌంటింగ్ మరియు ఫలితాలు',
    'timeline.event.5.date': 'సాధారణంగా మొదటి దశ తర్వాత 2-3 వారాలకు',
    'timeline.event.5.desc': 'ఓట్లను లెక్కిస్తారు మరియు ఎన్నికల సంఘం ఫలితాలను ప్రకటిస్తుంది.',
    'quiz.q1.question': 'భారతదేశంలో ఓటు వేయడానికి కనీస వయస్సు ఎంత?',
    'quiz.q1.options': '16 ఏళ్లు, 18 ఏళ్లు, 21 ఏళ్లు, 25 ఏళ్లు',
    'quiz.q1.explanation': '1988-వ సంవత్సరపు 61-వ రాజ్యాంగ సవరణ చట్టం, ఓటు వేసే వయస్సును 21 నుండి 18 సంవత్సరాలకు తగ్గించింది.',
    'quiz.q2.question': 'కొత్త ఓటరుగా నమోదు చేసుకోవడానికి ఏ ఫారమ్ ఉపయోగించబడుతుంది?',
    'quiz.q2.options': 'ఫారమ్ 6, ఫారమ్ 7, ఫారమ్ 8, ఫారమ్ 6A',
    'quiz.q2.explanation': "మొదటిసారి ఓటు వేసేవారు తమ పేరును ఓటరు జాబితాలో చేర్చుకోవడానికి 'ఫారమ్ 6' (Form 6) ఉపయోగిస్తారు.",
    'quiz.q3.question': 'NOTA అంటే ఏమిటి?',
    'quiz.q3.options': 'పైవేవీ కావు, ఇతర ప్రత్యామ్నాయం లేదు, ఎవరూ కాదు, తదుపరి అభ్యర్థి',
    'quiz.q3.explanation': 'NOTA (నోటా - ఏ అభ్యర్థికి ఓటు వేయడానికి ఇష్టం లేకపోతే) అనేది ఎన్నికలలో పోటీ చేస్తున్న అభ్యర్థులందరినీ అధికారికంగా తిరస్కరించే అవకాశాన్ని ఓటర్లకు కల్పిస్తుంది.',
    'quiz.q4.question': 'భారతదేశంలో లోక్‌సభ ఎన్నికలను ఎవరు నిర్వహిస్తారు?',
    'quiz.q4.options': 'భారత రాష్ట్రపతి, సుప్రీం కోర్టు, భారత ఎన్నికల సంఘం, పార్లమెంటు',
    'quiz.q4.explanation': 'భారత ఎన్నికల సంఘం అనేది భారతదేశంలో ఎన్నికల ప్రక్రియలను నిర్వహించడానికి బాధ్యత వహించే స్వయంప్రతిపత్తి కలిగిన రాజ్యాంగబద్ధమైన సంస్థ.',
    'quiz.q5.question': 'EPIC అంటే ఏమిటి?',
    'quiz.q5.options': 'ఓటరు ఫోటో గుర్తింపు కార్డు, ఎన్నికల సమాచార కార్డు, ఎలక్ట్రానిక్ పోలింగ్ గుర్తింపు కార్డు, ఎన్నికల ప్రక్రియ మండలి',
    'quiz.q5.explanation': 'EPIC అనేది భారత ఎన్నికల సంఘం జారీ చేసే ఓటరు గుర్తింపు కార్డు (Voter ID Card) యొక్క అధికారిక పదం.',
    'quiz.result.completed': 'క్విజ్ పూర్తయింది!',
    'quiz.result.score': 'మీ స్కోరు',
    'quiz.result.outOf': 'కి',
    'quiz.result.perfect': '🏆 అద్భుత విజయం! మీరు ఎన్నికలకు సిద్ధంగా ఉన్న పూర్తి అవగాహన కలిగిన ఓటరు!',
    'quiz.result.good': '👍 భేష్! ఓటింగ్ ప్రక్రియ గురించి మీకు మంచి అవగాహన ఉంది.',
    'quiz.result.learn': '📚 నేర్చుకుంటూ ఉండండి! ఓటింగ్ గురించి మీ సందేహాలను నివృత్తి చేసుకోవడానికి మా AI అసిస్టెంట్‌ని ఉపయోగించండి.',
    'quiz.result.retry': 'మళ్లీ ప్రయత్నించండి',
    'quiz.next': 'తదుపరి ప్రశ్న',
    'quiz.results': 'ఫలితాలను చూడండి',
    'quiz.explanation': 'వివరణ',
    'checklist.profile.title': 'మీ ఓటరు ప్రయాణాన్ని వ్యక్తిగతీకరించండి',
    'checklist.profile.age': 'మీ వయస్సు ఎంత?',
    'checklist.profile.agePlaceholder': '18+ ఉండాలి',
    'checklist.profile.firstTime': 'మీరు మొదటిసారి ఓటరా?',
    'checklist.profile.yes': 'అవును, నేను మొదటిసారి ఓటరును',
    'checklist.profile.no': 'లేదు, నేను ఇంతకు ముందు ఓటు వేశాను',
    'checklist.profile.state': 'మీరు ఏ రాష్ట్రం/కేంద్రపాలిత ప్రాంతంలో నివసిస్తున్నారు?',
    'checklist.profile.statePlaceholder': 'ఉదా. తెలంగాణ, ఆంధ్రప్రదేశ్...',
    'checklist.profile.submit': 'స్మార్ట్ చెక్‌లిస్ట్‌ను రూపొందించండి',
    'checklist.readiness': 'సంసిద్ధత స్కోరు',
    'checklist.done': 'పూర్తయినట్లు గుర్తు పెట్టండి',
    'checklist.complete.title': 'మీరు ఎన్నికలకు సిద్ధంగా ఉన్నారు! 🎉',
    'checklist.complete.desc': 'మీ ప్రొఫైల్ 100% పూర్తయింది. మీ గొంతు ముఖ్యం, మీరు వెళ్లి ఓటు వేసేలా చూసుకోండి!',
    'checklist.step1.title': 'అర్హతను తనిఖీ చేయండి',
    'checklist.step1.desc': 'మీరు భారతీయ పౌరులని మరియు అర్హత తేదీ నాటికి 18 ఏళ్లు పైబడిన వారని నిర్ధారించుకోండి.',
    'checklist.step1.details': 'నిర్దిష్ట నేరాలు లేదా అవినీతి పద్ధతుల కారణంగా మీరు అనర్హులైతే మీరు ఓటు వేయలేరు.',
    'checklist.step2.title': 'పత్రాలను సేకరించండి',
    'checklist.step2.desc': 'మీ వయస్సు మరియు చిరునామా ధృవీకరణ పత్రాలను సేకరించండి.',
    'checklist.step2.details': 'చెల్లుబాటు అయ్యే రుజువులలో ఆధార్ కార్డ్, పాస్‌పోర్ట్, డ్రైవింగ్ లైసెన్స్, పాన్ కార్డ్ లేదా 10/12వ తరగతి సర్టిఫికేట్ ఉన్నాయి.',
    'checklist.step3.title': 'ఫారమ్ 6 నింపండి',
    'checklist.step3.desc': 'ఓటర్ సర్వీస్ పోర్టల్‌లో ఆన్‌లైన్‌లో లేదా మీ BLO ద్వారా ఆఫ్‌లైన్‌లో దరఖాస్తు చేసుకోండి.',
    'checklist.step3.details': 'voters.eci.gov.in కి వెళ్లి, రిజిస్టర్/లాగిన్ అవ్వండి మరియు కొత్త ఓటరు నమోదు కోసం ఫారమ్ 6ని నింపండి. మీ ఫోటో మరియు పత్రాలను అప్‌లోడ్ చేయండి.',
    'checklist.step4.title': 'ధృవీకరణ',
    'checklist.step4.desc': 'బూత్ స్థాయి అధికారి (BLO) మీ వివరాలను ధృవీకరిస్తారు.',
    'checklist.step4.details': 'అందించిన వివరాలను ధృవీకరించడానికి ఒక BLO మీ చిరునామాను సందర్శించవచ్చు. మీ అసలు పత్రాలను అందుబాటులో ఉంచుకోండి.',
    'checklist.step5.title': 'ఓటరు ఐడి (EPIC) పొందండి',
    'checklist.step5.desc': 'e-EPIC డౌన్‌లోడ్ చేసుకోండి లేదా భౌతిక డెలివరీ కోసం వేచి ఉండండి.',
    'checklist.step5.details': 'ఆమోదించబడిన తర్వాత, మీ పేరు ఓటరు జాబితాలో చేర్చబడుతుంది. మీరు పోర్టల్ నుండి డిజిటల్ కాపీని (e-EPIC) డౌన్‌లోడ్ చేసుకోవచ్చు.',
    'checklist.step6.title': 'ఎన్నికల రోజున ఓటు వేయండి',
    'checklist.step6.desc': 'మీ పోలింగ్ బూత్‌ను కనుగొని మీ ఓటు వేయండి!',
    'checklist.step6.details': 'ఓటరు స్లిప్‌పై మీ పేరును తనిఖీ చేయండి, మీ EPIC లేదా ఇతర చెల్లుబాటు అయ్యే ఐడిని తీసుకెళ్లండి మరియు EVMపై బటన్‌ను నొక్కండి!',
    'features.section.title': 'ఆధునిక ఓటరు కోసం శక్తివంతమైన ఫీచర్లు',
    'features.section.subtitle': 'ప్రపంచంలోని అతిపెద్ద ప్రజాస్వామ్యంలో పాల్గొనడానికి మీకు కావలసినవన్నీ, AI ద్వారా సరళీకరించబడ్డాయి.',
    'stats.voters.label': 'క్రియాశీల ఓటర్లు',
    'stats.voters.value': '960M+',
    'stats.stations.label': 'పోలింగ్ కేంద్రాలు',
    'stats.stations.value': '1M+',
    'stats.queries.label': 'AI ప్రశ్నలు పరిష్కరించబడ్డాయి',
    'stats.queries.value': '500K+',
    'stats.languages.label': 'మద్దతు ఇచ్చే భాషలు',
    'stats.languages.value': '12+',
    'how.title': 'ఓటింగ్ వైపు మీ ప్రయాణం',
    'how.step1.title': 'నమోదు చేసుకోండి',
    'how.step1.desc': 'మీ ప్రొఫైల్‌ను సృష్టించండి మరియు రాబోయే ఎన్నికలకు మీ అర్హతను తనిఖీ చేయండి.',
    'how.step2.title': 'ధృవీకరించండి',
    'how.step2.desc': 'మీకు ఏ పత్రాలు అవసరమో అర్థం చేసుకోవడానికి మా AI అసిస్టెంట్‌ని ఉపయోగించండి.',
    'how.step3.title': 'సిద్ధం అవ్వండి',
    'how.step3.desc': 'ముఖ్యమైన తేదీలను ట్రాక్ చేయండి మరియు మా మ్యాప్‌తో మీ బూత్‌ను కనుగొనండి.',
    'how.step4.title': 'ఓటు వేయండి',
    'how.step4.desc': 'బయటకు వెళ్లి మీ గొంతును వినిపించండి. మీ ఓటు దేశ భవిష్యత్తును నిర్ణయిస్తుంది.',
    'cta.title': 'భవిష్యత్తును తీర్చిదిద్దడానికి సిద్ధంగా ఉన్నారా?',
    'cta.desc': 'ప్రపంచంలోని అతిపెద్ద ప్రజాస్వామ్య ప్రక్రియలో మిలియన్ల మంది భారతీయ పౌరులతో చేరండి.',
    'cta.reg': 'ఇప్పుడే నమోదు చేసుకోండి',
    'cta.learn': 'మరింత తెలుసుకోండి',
    'hero.scroll': 'అన్వేషించడానికి స్క్రోల్ చేయండి'
  },
  bn: {
    'nav.home': 'হোম',
    'nav.assistant': 'এআই সহকারী',
    'nav.timeline': 'টাইমলাইন',
    'nav.quiz': 'কুইজ',
    'nav.checklist': 'চেকলিস্ট',
    'nav.map': 'বুথ ম্যাপ',
    'hero.title': 'আপনার ভয়েস, আপনার ভোট',
    'hero.subtitle': 'ভারতীয় ভোটারদের জন্য এআই গাইড। জানুন এবং প্রস্তুত হন।',
    'hero.cta': 'শুরু করুন',
    'hero.cta2': 'সহকারীকে জিজ্ঞাসা করুন',
    'features.assistant.title': 'এআই নির্বাচন সহকারী',
    'features.assistant.desc': 'ভোটদান প্রক্রিয়া সম্পর্কে আপনার পছন্দের ভাষায় প্রশ্ন জিজ্ঞাসা করুন।',
    'features.timeline.title': 'ভোটার টাইমলাইন',
    'features.timeline.desc': 'নিবন্ধন থেকে ফলাফল পর্যন্ত নির্বাচন প্রক্রিয়া ট্র্যাক করুন।',
    'features.checklist.title': 'প্রথমবারের ভোটার গাইড',
    'features.checklist.desc': 'নিবন্ধন করতে এবং ভোট দেওয়ার জন্য ধাপে ধাপে চেকলিস্ট।',
    'features.map.title': 'পোলিং বুথ খুঁজুন',
    'features.map.desc': 'আপনার কাছাকাছি পোলিং বুথ খুঁজুন।',
    'explore': 'অন্বেষণ করুন',
    'checklist.title': 'প্রথমবারের ভোটার যাত্রা',
    'checklist.subtitle': 'ভারতে নিবন্ধিত ভোটার হওয়ার জন্য আপনার ধাপে ধাপে চেকলিস্ট।',
    'checklist.progress': 'আপনার অগ্রগতি',
    'checklist.step': 'ধাপ',
    'checklist.completed': 'ধাপ সম্পন্ন হয়েছে',
    'timeline.title': 'নির্বাচন টাইমলাইন',
    'timeline.subtitle': 'ভারতে গণতান্ত্রিক প্রক্রিয়ার পর্যায়গুলি বুঝুন।',
    'quiz.title': 'ভোটার সচেতনতা কুইজ',
    'quiz.subtitle': 'নির্বাচন প্রক্রিয়া সম্পর্কে আপনার জ্ঞান পরীক্ষা করুন!',
    'map.title': 'পোলিং বুথ খুঁজুন',
    'map.subtitle': 'আপনার বর্তমান অবস্থানের কাছাকাছি পোলিং বুথ খুঁজুন।',
    'assistant.title': 'VoteIndia সহকারী',
    'assistant.subtitle': 'Google AI দ্বারা চালিত',
    'assistant.placeholder': 'আপনার প্রশ্ন এখানে টাইপ করুন...',
    'assistant.listening': 'শুনছি...',
    'assistant.greeting': 'নমস্কার! আমি আপনার এআই নির্বাচন সহকারী। আমি আজ কীভাবে আপনাকে সাহায্য করতে পারি?',
    'assistant.suggestions.1': 'আমি কীভাবে ভোট দেওয়ার জন্য নিবন্ধন করব?',
    'assistant.suggestions.2': 'আমার কী কী নথিপত্রের প্রয়োজন?',
    'assistant.suggestions.3': 'ভোটার তালিকায় আমার নাম কীভাবে চেক করব?',
    'assistant.suggestions.4': 'ভারতে ভোট দেওয়ার সর্বনিম্ন বয়স কত?',
    'timeline.badge': 'প্রক্রিয়াটি বুঝুন',
    'timeline.event.1.title': 'ভোটার নিবন্ধন',
    'timeline.event.1.date': 'চলমান - নির্বাচনের আগে বন্ধ হয়',
    'timeline.event.1.desc': 'ভোটার তালিকায় আপনার নাম আছে কিনা নিশ্চিত করুন। আপনি যদি নতুন ভোটার হন তবে ফর্ম ৬ এর মাধ্যমে আবেদন করুন।',
    'timeline.event.2.title': 'নির্বাচনী তফসিল ঘোষণা',
    'timeline.event.2.date': 'আদর্শ আচরণবিধি কার্যকর হয়',
    'timeline.event.2.desc': 'ভারতের নির্বাচন কমিশন (ECI) ভোটগ্রহণের তারিখ, পর্যায় এবং গণনার দিন ঘোষণা করে।',
    'timeline.event.3.title': 'প্রচারণার সময়কাল',
    'timeline.event.3.date': 'ভোটগ্রহণের ৪৮ ঘণ্টা আগে শেষ হয়',
    'timeline.event.3.desc': 'প্রার্থীরা প্রচারণা চালান এবং ইশতেহার প্রকাশ করেন। আপনার নির্বাচনী এলাকার প্রার্থীদের সম্পর্কে গবেষণা করার সময়।',
    'timeline.event.4.title': 'ভোটের দিন',
    'timeline.event.4.date': 'আপনার পর্যায়/নির্বাচনী এলাকা অনুযায়ী',
    'timeline.event.4.desc': 'আপনার নির্ধারিত ভোটকেন্দ্রে যান। ইভিএম-এ আপনার পছন্দের প্রার্থীর বিপরীতে বোতামটি টিপুন।',
    'timeline.event.5.title': 'গণনা এবং ফলাফল',
    'timeline.event.5.date': 'সাধারণত প্রথম পর্যায়ের ২-৩ সপ্তাহ পরে',
    'timeline.event.5.desc': 'ভোট গণনা করা হয় এবং নির্বাচন কমিশন ফলাফল ঘোষণা করে।',
    'quiz.q1.question': 'ভারতে ভোট দেওয়ার সর্বনিম্ন বয়স কত?',
    'quiz.q1.options': '১৬ বছর, ১৮ বছর, ২১ বছর, ২৫ বছর',
    'quiz.q1.explanation': '১৯৮৮ সালের ৬১তম সংবিধান সংশোধনী আইন ভোটাধিকারের বয়স ২১ থেকে কমিয়ে ১৮ বছর করেছে।',
    'quiz.q2.question': 'নতুন ভোটার হিসেবে নিবন্ধন করতে কোন ফর্ম ব্যবহার করা হয়?',
    'quiz.q2.options': 'ফর্ম ৬, ফর্ম ৭, ফর্ম ৮, ফর্ম ৬এ',
    'quiz.q2.explanation': "প্রথমবার ভোটারদের ভোটার তালিকায় নাম অন্তর্ভুক্ত করার জন্য 'ফর্ম ৬' ব্যবহার করা হয়।",
    'quiz.q3.question': 'NOTA-এর পূর্ণরূপ কী?',
    'quiz.q3.options': 'উপরের কোনটিই নয়, অন্য কোনো বিকল্প নেই, কেউ নয়, পরবর্তী',
    'quiz.q3.explanation': 'NOTA (নোট) ভোটারদের নির্বাচনে প্রতিদ্বন্দ্বী সকল প্রার্থীকে আনুষ্ঠানিকভাবে প্রত্যাখ্যান করার সুযোগ দেয়।',
    'quiz.q4.question': 'ভারতে লোকসভা নির্বাচন কে পরিচালনা করে?',
    'quiz.q4.options': 'ভারতের রাষ্ট্রপতি, সুপ্রিম কোর্ট, ভারতের নির্বাচন কমিশন, সংসদ',
    'quiz.q4.explanation': 'ভারতের নির্বাচন কমিশন একটি স্বায়ত্তশাসিত সাংবিধানিক কর্তৃপক্ষ, যা ভারতে নির্বাচন প্রক্রিয়া পরিচালনার দায়িত্বে রয়েছে।',
    'quiz.q5.question': 'EPIC কী?',
    'quiz.q5.options': 'ভোটার ছবি পরিচয়পত্র, নির্বাচনী প্যানেল তথ্য কার্ড, ইলেকট্রনিক পোলিং পরিচয়পত্র, নির্বাচনী প্রক্রিয়া কাউন্সিল',
    'quiz.q5.explanation': 'EPIC হলো ভারতের নির্বাচন কমিশন কর্তৃক ইস্যুকৃত ভোটার আইডি কার্ডের আনুষ্ঠানিক নাম।',
    'quiz.result.completed': 'প্রানিভিত্তি সম্পন্ন!',
    'quiz.result.score': 'আপনার স্কোর',
    'quiz.result.outOf': 'এর মধ্যে',
    'quiz.result.perfect': '🏆 নিখুঁত জয়! আপনি একজন সম্পূর্ণ সচেতন ভোটার যিনি নির্বাচনের জন্য প্রস্তুত!',
    'quiz.result.good': '👍 চমৎকার কাজ! আপনার ভোটদান প্রক্রিয়া সম্পর্কে ভালো ধারণা আছে।',
    'quiz.result.learn': '📚 শিখতে থাকুন! ভোট সম্পর্কে আপনার সন্দেহ দূর করতে আমাদের এআই সহকারী ব্যবহার করুন।',
    'quiz.result.retry': 'পুনরায় চেষ্টা করুন',
    'quiz.next': 'পরবর্তী প্রশ্ন',
    'quiz.results': 'ফলাফল দেখুন',
    'quiz.explanation': 'ব্যাখ্যা',
    'checklist.profile.title': 'আপনার ভোটার যাত্রাকে ব্যক্তিগতকৃত করুন',
    'checklist.profile.age': 'আপনার বয়স কত?',
    'checklist.profile.agePlaceholder': 'অবশ্যই ১৮+ হতে হবে',
    'checklist.profile.firstTime': 'আপনি কি প্রথমবার ভোটার?',
    'checklist.profile.yes': 'হ্যাঁ, আমি প্রথমবার ভোটার',
    'checklist.profile.no': 'না, আমি আগে ভোট দিয়েছি',
    'checklist.profile.state': 'আপনি কোন রাজ্য/কেন্দ্রশাসিত অঞ্চলে বাস করেন?',
    'checklist.profile.statePlaceholder': 'যেমন- পশ্চিমবঙ্গ, ত্রিপুরা...',
    'checklist.profile.submit': 'স্মার্ট চেকলিস্ট তৈরি করুন',
    'checklist.readiness': 'প্রস্তুতি স্কোর',
    'checklist.done': 'সম্পন্ন হিসেবে চিহ্নিত করুন',
    'checklist.complete.title': 'আপনি নির্বাচনের জন্য প্রস্তুত! 🎉',
    'checklist.complete.desc': 'আপনার প্রোফাইল ১০০% সম্পন্ন হয়েছে। আপনার কণ্ঠস্বর গুরুত্বপূর্ণ, নিশ্চিত করুন যে আপনি বাইরে গিয়ে ভোট দিচ্ছেন!',
    'checklist.step1.title': 'যোগ্যতা যাচাই করুন',
    'checklist.step1.desc': 'নিশ্চিত করুন যে আপনি একজন ভারতীয় নাগরিক এবং যোগ্যতার তারিখে আপনার বয়স ১৮+ বছর।',
    'checklist.step1.details': 'কিছু অপরাধ বা দুর্নীতিমূলক আচরণের কারণে আপনি অযোগ্য ঘোষিত হলে আপনি ভোট দিতে পারবেন না।',
    'checklist.step2.title': 'নথিপত্র সংগ্রহ করুন',
    'checklist.step2.desc': 'আপনার বয়স এবং ঠিকানার প্রমাণপত্র সংগ্রহ করুন।',
    'checklist.step2.details': 'বৈধ প্রমাণের মধ্যে আধার কার্ড, পাসপোর্ট, ড্রাইভিং লাইসেন্স, প্যান কার্ড বা ১০ম/১২ম শ্রেণীর প্রশংসাপত্র অন্তর্ভুক্ত।',
    'checklist.step3.title': 'ফর্ম ৬ পূরণ করুন',
    'checklist.step3.desc': 'ভোটার সার্ভিস পোর্টালে অনলাইনে বা আপনার BLO-এর মাধ্যমে অফলাইনে আবেদন করুন।',
    'checklist.step3.details': 'voters.eci.gov.in-এ যান, নিবন্ধন/লগইন করুন এবং নতুন ভোটার নিবন্ধনের জন্য ফর্ম ৬ পূরণ করুন। আপনার ছবি এবং নথিপত্র আপলোড করুন।',
    'checklist.step4.title': 'যাচাইকরণ',
    'checklist.step4.desc': 'বুথ লেভেল অফিসার (BLO) আপনার বিবরণ যাচাই করবেন।',
    'checklist.step4.details': 'প্রদত্ত বিবরণ যাচাই করার জন্য একজন BLO আপনার ঠিকানায় আসতে পারেন। আপনার আসল নথিপত্র সাথে রাখুন।',
    'checklist.step5.title': 'ভোটার আইডি (EPIC) পান',
    'checklist.step5.desc': 'ই-ইপিক ডাউনলোড করুন বা ফিজিক্যাল ডেলিভারির জন্য অপেক্ষা করুন।',
    'checklist.step5.details': 'অনুমোদিত হওয়ার পরে, আপনার নাম ভোটার তালিকায় অন্তর্ভুক্ত করা হবে। আপনি পোর্টাল থেকে ডিজিটাল কপি (e-EPIC) ডাউনলোড করতে পারেন।',
    'checklist.step6.title': 'নির্বাচনের দিন ভোট দিন',
    'checklist.step6.desc': 'আপনার পোলিং বুথ খুঁজে বের করুন এবং ভোট দিন!',
    'checklist.step6.details': 'ভোটার স্লিপে আপনার নাম চেক করুন, আপনার ইপিক বা অন্য কোনো বৈধ আইডি সাথে নিন এবং ইভিএম-এর বোতাম টিপুন!',
    'features.section.title': 'আধুনিক ভোটারের জন্য শক্তিশালী বৈশিষ্ট্য',
    'features.section.subtitle': 'বিশ্বের বৃহত্তম গণতন্ত্রে অংশগ্রহণের জন্য আপনার যা কিছু প্রয়োজন, এআই দ্বারা সরলীকৃত।',
    'stats.voters.label': 'সক্রিয় ভোটার',
    'stats.voters.value': '960M+',
    'stats.stations.label': 'ভোটকেন্দ্র',
    'stats.stations.value': '1M+',
    'stats.queries.label': 'এআই সমস্যার সমাধান',
    'stats.queries.value': '500K+',
    'stats.languages.label': 'সমর্থিত ভাষা',
    'stats.languages.value': '12+',
    'how.title': 'ভোটদানের দিকে আপনার যাত্রা',
    'how.step1.title': 'নিবন্ধন করুন',
    'how.step1.desc': 'আপনার প্রোফাইল তৈরি করুন এবং আসন্ন নির্বাচনের জন্য আপনার যোগ্যতা যাচাই করুন।',
    'how.step2.title': 'যাচাই করুন',
    'how.step2.desc': 'আপনার কী কী নথিপত্র প্রয়োজন তা বুঝতে আমাদের এআই সহকারী ব্যবহার করুন।',
    'how.step3.title': 'প্রস্তুত হন',
    'how.step3.desc': 'গুরুত্বপূর্ণ তারিখগুলি ট্র্যাক করুন এবং আমাদের ম্যাপের সাহায্যে আপনার বুথ খুঁজুন।',
    'how.step4.title': 'ভোট দিন',
    'how.step4.desc': 'বাইরে যান এবং আপনার কণ্ঠস্বর তুলুন। আপনার ভোট দেশের ভবিষ্যৎ গঠন করে।',
    'cta.title': 'ভবিষ্যত গঠনের জন্য প্রস্তুত?',
    'cta.desc': 'বিশ্বের বৃহত্তম গণতান্ত্রিক প্রক্রিয়ায় লক্ষ লক্ষ ভারতীয় নাগরিকের সাথে যোগ দিন।',
    'cta.reg': 'এখনই নিবন্ধন করুন',
    'cta.learn': 'আরও জানুন',
    'hero.scroll': 'অন্বেষণ করতে স্ক্রোল করুন'
  },
  mr: {
    'nav.home': 'मुख्यपृष्ठ',
    'nav.assistant': 'एआय सहाय्यक',
    'nav.timeline': 'वेळापत्रक',
    'nav.quiz': 'क्विझ',
    'nav.checklist': 'चेकलिस्ट',
    'nav.map': 'बूथ नकाशा',
    'hero.title': 'तुमचा आवाज, तुमचे मत',
    'hero.subtitle': 'भारतीय मतदारांसाठी एआय मार्गदर्शक. माहिती मिळवा आणि तयार राहा.',
    'hero.cta': 'सुरुवात करा',
    'hero.cta2': 'सहाय्यकाला विचारा',
    'features.assistant.title': 'एआय निवडणूक सहाय्यक',
    'features.assistant.desc': 'मतदान प्रक्रियेबद्दल आपल्या पसंतीच्या भाषेत प्रश्न विचारा.',
    'features.timeline.title': 'मतदार वेळापत्रक',
    'features.timeline.desc': 'नोंदणीपासून निकालापर्यंत निवडणूक प्रक्रियेचा मागोवा घ्या.',
    'features.checklist.title': 'पहिल्यांदा मतदार मार्गदर्शक',
    'features.checklist.desc': 'नोंदणी करण्यासाठी आणि मतदान करण्यासाठी टप्प्याटप्प्याने चेकलिस्ट.',
    'features.map.title': 'मतदान केंद्र शोधा',
    'features.map.desc': 'आपल्या जवळचे मतदान केंद्र शोधा.',
    'explore': 'अधिक एक्सप्लोर करा',
    'checklist.title': 'पहिल्यांदा मतदार प्रवास',
    'checklist.subtitle': 'भारतात नोंदणीकृत मतदार होण्यासाठी तुमची टप्प्याटप्प्याने चेकलिस्ट.',
    'checklist.progress': 'तुमची प्रगती',
    'checklist.step': 'पायरी',
    'checklist.completed': 'पायऱ्या पूर्ण झाल्या',
    'timeline.title': 'निवडणूक वेळापत्रक',
    'timeline.subtitle': 'भारतातील लोकशाही प्रक्रियेचे टप्पे समजून घ्या.',
    'quiz.title': 'मतदार जागरूकता क्विझ',
    'quiz.subtitle': 'भारतीय निवडणूक प्रक्रियेबद्दल आपल्या ज्ञानाची चाचणी घ्या!',
    'map.title': 'मतदान केंद्र शोधा',
    'map.subtitle': 'आपल्या वर्तमान स्थानाजवळ मतदान केंद्रे शोधा.',
    'assistant.title': 'VoteIndia सहाय्यक',
    'assistant.subtitle': 'Google AI द्वारे समर्थित',
    'assistant.placeholder': 'तुमचा प्रश्न येथे टाइप करा...',
    'assistant.listening': 'ऐकत आहे...',
    'assistant.greeting': 'नमस्कार! मी तुमचा एआय निवडणूक सहाय्यक आहे. मी आज तुम्हाला कशी मदत करू शकतो?',
    'assistant.suggestions.1': 'मी मतदानासाठी नोंदणी कशी करू?',
    'assistant.suggestions.2': 'मला कोणती कागदपत्रे लागतील?',
    'assistant.suggestions.3': 'मतदार यादीत माझे नाव कसे तपासावे?',
    'assistant.suggestions.4': 'भारतात मतदानाचे किमान वय किती आहे?',
    'timeline.badge': 'प्रक्रिया समजून घ्या',
    'timeline.event.1.title': 'मतदार नोंदणी',
    'timeline.event.1.date': 'सुरू आहे - निवडणुकीपूर्वी थांबते',
    'timeline.event.1.desc': 'मतदार यादीत तुमचे नाव असल्याची खात्री करा. तुम्ही नवीन मतदार असल्यास फॉर्म ६ द्वारे अर्ज करा.',
    'timeline.event.2.title': 'निवडणूक वेळापत्रकाची घोषणा',
    'timeline.event.2.date': 'आदर्श आचारसंहिता लागू',
    'timeline.event.2.desc': 'भारतीय निवडणूक आयोग (ECI) मतदानाची तारीख, टप्पे आणि मतमोजणीचा दिवस जाहीर करतो.',
    'timeline.event.3.title': 'प्रचार कालावधी',
    'timeline.event.3.date': 'मतदानाच्या ४८ तास आधी संपतो',
    'timeline.event.3.desc': 'उमेदवार प्रचार करतात आणि जाहीरनामे प्रसिद्ध करतात. तुमच्या मतदारसंघातील उमेदवारांबद्दल संशोधन करण्याची हीच वेळ आहे.',
    'timeline.event.4.title': 'मतदानाचा दिवस',
    'timeline.event.4.date': 'तुमच्या टप्प्यानुसार/मतदारसंघाप्रमाणे',
    'timeline.event.4.desc': 'तुमच्या नियुक्त मतदान केंद्रावर जा. ईव्हीएमवर तुमच्या पसंतीच्या उमेदवारासमोरील बटण दाबा.',
    'timeline.event.5.title': 'मतमोजणी आणि निकाल',
    'timeline.event.5.date': 'साधारणपणे पहिल्या टप्प्यानंतर २-३ आठवड्यांनी',
    'timeline.event.5.desc': 'मतांची मोजणी केली जाते आणि निवडणूक आयोगाद्वारे निकाल जाहीर केले जातात.',
    'quiz.q1.question': 'भारतात मतदानाचे किमान वय किती आहे?',
    'quiz.q1.options': '१६ वर्षे, १८ वर्षे, २१ वर्षे, २५ वर्षे',
    'quiz.q1.explanation': '१९८८ च्या ६१ व्या घटनादुरुस्ती कायद्याने मतदानाचे वय २१ वरून १८ वर्षांपर्यंत कमी केले.',
    'quiz.q2.question': 'नवीन मतदार म्हणून नोंदणी करण्यासाठी कोणता फॉर्म वापरला जातो?',
    'quiz.q2.options': 'फॉर्म ६, फॉर्म ७, फॉर्म ८, फॉर्म ६ए',
    'quiz.q2.explanation': "पहिल्यांदा मतदान करणाऱ्यांसाठी मतदार यादीत नाव समाविष्ट करण्यासाठी 'फॉर्म ६' (Form 6) चा वापर केला जातो.",
    'quiz.q3.question': 'NOTA चा अर्थ काय?',
    'quiz.q3.options': 'यापैकी काहीही नाही, दुसरा पर्याय नाही, कोणीही नाही, पुढचा',
    'quiz.q3.explanation': 'NOTA (नोटा - वरीलपैकी कोणीही नाही) मतदारांना निवडणुकीत उभे असलेल्या सर्व उमेदवारांना अधिकृतपणे नाकारण्याची संधी देते.',
    'quiz.q4.question': 'भारतात लोकसभेच्या निवडणुका कोण घेते?',
    'quiz.q4.options': 'भारताचे राष्ट्रपती, सर्वोच्च न्यायालय, भारतीय निवडणूक आयोग, संसद',
    'quiz.q4.explanation': 'भारतीय निवडणूक आयोग ही एक स्वायत्त घटनात्मक संस्था असून ती भारतातील निवडणूक प्रक्रिया राबवण्यासाठी जबाबदार आहे.',
    'quiz.q5.question': 'EPIC म्हणजे काय?',
    'quiz.q5.options': 'मतदार फोटो ओळखपत्र, निवडणूक पॅनेल माहिती कार्ड, इलेक्ट्रॉनिक पोलिंग ओळखपत्र, निवडणूक प्रक्रिया परिषद',
    'quiz.q5.explanation': 'ईपीआयसी (EPIC) हे भारतीय निवडणूक आयोगाद्वारे जारी केलेल्या मतदार ओळखपत्राचे अधिकृत नाव आहे.',
    'quiz.result.completed': 'चाचणी पूर्ण झाली!',
    'quiz.result.score': 'तुमचा स्कोअर',
    'quiz.result.outOf': 'पैकी',
    'quiz.result.perfect': '🏆 शानदार विजय! तुम्ही निवडणुकीसाठी पूर्णपणे तयार असलेले जागरूक मतदार आहात!',
    'quiz.result.good': '👍 उत्तम! तुम्हाला मतदान प्रक्रियेबद्दल चांगली माहिती आहे.',
    'quiz.result.learn': '📚 शिकत राहा! मतदानाबद्दलच्या तुमच्या शंका दूर करण्यासाठी आमच्या एआई सहाय्यकाचा वापर करा.',
    'quiz.result.retry': 'पुन्हा प्रयत्न करा',
    'quiz.next': 'पुढील प्रश्न',
    'quiz.results': 'निकाल पहा',
    'quiz.explanation': 'स्पष्टीकरण',
    'checklist.profile.title': 'तुमचा मतदार प्रवास वैयक्तिकृत करा',
    'checklist.profile.age': 'तुमचे वय काय आहे?',
    'checklist.profile.agePlaceholder': '१८+ असणे आवश्यक आहे',
    'checklist.profile.firstTime': 'तुम्ही पहिल्यांदाच मतदान करणार आहात का?',
    'checklist.profile.yes': 'हो, मी पहिल्यांदाच मतदान करणार आहे',
    'checklist.profile.no': 'नाही, मी यापूर्वी मतदान केले आहे',
    'checklist.profile.state': 'तुम्ही कोणत्या राज्य/केंद्रशासित प्रदेशात राहता?',
    'checklist.profile.statePlaceholder': 'उदा. महाराष्ट्र, गोवा...',
    'checklist.profile.submit': 'स्मार्ट चेकलिस्ट तयार करा',
    'checklist.readiness': 'सज्जता स्कोअर',
    'checklist.done': 'पूर्ण झाल्याचे चिन्हांकित करा',
    'checklist.complete.title': 'तुम्ही निवडणुकीसाठी सज्ज आहात! 🎉',
    'checklist.complete.desc': 'तुमचे प्रोफाइल १००% पूर्ण झाले आहे. तुमचा आवाज महत्त्वाचा आहे, तुम्ही बाहेर पडून मतदान केल्याची खात्री करा!',
    'checklist.step1.title': 'पात्रता तपासा',
    'checklist.step1.desc': 'तुम्ही भारतीय नागरिक आणि पात्रता तारखेला १८+ वयाचे असल्याची खात्री करा.',
    'checklist.step1.details': 'काही गुन्ह्यांमुळे किंवा भ्रष्ट आचरणामुळे तुम्ही अपात्र ठरला असाल तर तुम्ही मतदान करू शकत नाही.',
    'checklist.step2.title': 'कागदपत्रे गोळा करा',
    'checklist.step2.desc': 'तुमच्या वयाचा आणि पत्त्याचा पुरावा गोळा करा.',
    'checklist.step2.details': 'वैध पुराव्यांमध्ये आधार कार्ड, पासपोर्ट, ड्रायव्हिंग लायसन्स, पॅन कार्ड किंवा १० वी/१२ वीचे प्रमाणपत्र यांचा समावेश होतो.',
    'checklist.step3.title': 'फॉर्म ६ भरा',
    'checklist.step3.desc': 'व्होटर सर्व्हिस पोर्टलवर ऑनलाईन किंवा तुमच्या BLO द्वारे ऑफलाईन अर्ज करा.',
    'checklist.step3.details': 'voters.eci.gov.in वर जा, नोंदणी/लॉगिन करा आणि नवीन मतदार नोंदणीसाठी फॉर्म ६ भरा. तुमचा फोटो आणि कागदपत्रे अपलोड करा.',
    'checklist.step4.title': 'पडताळणी',
    'checklist.step4.desc': 'बूथ लेव्हल ऑफिसर (BLO) तुमच्या तपशीलांची पडताळणी करतील.',
    'checklist.step4.details': 'दिलेल्या तपशीलांची पडताळणी करण्यासाठी एखादा BLO तुमच्या पत्त्यावर येऊ शकतो. तुमची मूळ कागदपत्रे तयार ठेवा.',
    'checklist.step5.title': 'मतदार ओळखपत्र (EPIC) मिळवा',
    'checklist.step5.desc': 'ई-ईपीआयसी डाउनलोड करा किंवा प्रत्यक्ष वितरणाची प्रतीक्षा करा.',
    'checklist.step5.details': 'एकदा मंजूर झाल्यानंतर, तुमचे नाव मतदार यादीत जोडले जाईल. तुम्ही पोर्टलवरून डिजिटल प्रत (e-EPIC) डाउनलोड करू शकता.',
    'checklist.step6.title': 'निवडणुकीच्या दिवशी मतदान करा',
    'checklist.step6.desc': 'तुमचे मतदान केंद्र शोधा आणि तुमचे मत द्या!',
    'checklist.step6.details': 'मतदार स्लिपवर तुमचे नाव तपासा, तुमचे ईपीआयसी किंवा इतर वैध ओळखपत्र सोबत घ्या आणि ईव्हीएमवरील बटण दाबा!',
    'features.section.title': 'आधुनिक मतदारासाठी शक्तिशाली वैशिष्ट्ये',
    'features.section.subtitle': 'जगातील सर्वात मोठ्या लोकशाहीत सहभागी होण्यासाठी तुम्हाला आवश्यक असलेले सर्व काही, AI द्वारे सरलीकृत।',
    'stats.voters.label': 'सक्रिय मतदार',
    'stats.voters.value': '960M+',
    'stats.stations.label': 'मतदान केंद्रे',
    'stats.stations.value': '1M+',
    'stats.queries.label': 'एआय प्रश्न सोडवले',
    'stats.queries.value': '500K+',
    'stats.languages.label': 'समर्थित भाषा',
    'stats.languages.value': '12+',
    'how.title': 'मतदानाकडे तुमचा प्रवास',
    'how.step1.title': 'नोंदणी करा',
    'how.step1.desc': 'तुमचे प्रोफाइल तयार करा आणि आगामी निवडणुकांसाठी तुमची पात्रता तपासा।',
    'how.step2.title': 'पडताळणी',
    'how.step2.desc': 'तुम्हाला कोणत्या कागदपत्रांची आवश्यकता आहे हे समजून घेण्यासाठी आमच्या एआय सहाय्यकाचा वापर करा।',
    'how.step3.title': 'तयार राहा',
    'how.step3.desc': 'महत्वाच्या तारखांचा मागोवा घ्या आणि आमच्या नकाशासह तुमचे बूथ शोधा।',
    'how.step4.title': 'मतदान करा',
    'how.step4.desc': 'बाहेर पडा आणि तुमचा आवाज उठवा। तुमचे मत देशाचे भविष्य घडवते।',
    'cta.title': 'भविष्य घडवण्यासाठी सज्ज आहात?',
    'cta.desc': 'जगातील सर्वात मोठ्या लोकशाही सरावात लाखो भारतीय नागरिकांसह सामील व्हा।',
    'cta.reg': 'आता नोंदणी करा',
    'cta.learn': 'अधिक जाणून घ्या',
    'hero.scroll': 'एक्सप्लोर करण्यासाठी स्क्रोल करा'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');
  const [isInitialized, setIsInitialized] = useState(false);

  useEffect(() => {
    try {
      const saved = localStorage.getItem('voteIndia_language');
      if (saved && ['en', 'hi', 'ta', 'te', 'bn', 'mr'].includes(saved)) {
        setLanguageState(saved as Language);
        document.documentElement.lang = saved;
      } else {
        document.documentElement.lang = 'en';
      }
    } catch (e) {
      console.warn("localStorage not available", e);
      document.documentElement.lang = 'en';
    } finally {
      setIsInitialized(true);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('voteIndia_language', lang);
    } catch (e) {
      console.warn("localStorage not available", e);
    }
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    // @ts-ignore
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  if (!isInitialized) return null; // Or a subtle loader to prevent hydration mismatch

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
